apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: streamin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  volumeName: media
