---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv
  namespace: streamin
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: conv
  template:
    metadata:
      labels:
        k8s-app: conv
    spec:
      containers:
      - image: davmatjo/streamin-conv:sha-0441d5af
        imagePullPolicy: Always
        name: conv
        ports:
        - containerPort: 8090
          protocol: TCP
        volumeMounts:
        - mountPath: /app/out
          name: media
        - mountPath: /app/in
          name: ingest
        - mountPath: /app/config.yaml
          name: config
          subPath: config.yaml
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: ingest
        persistentVolumeClaim:
          claimName: ingest
      - name: config
        configMap:
          name: conv
